repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-symlinks
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^./expt-logs/
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^./expt-logs/
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^./expt-logs/
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100']
  # - repo: https://github.com/pycqa/bandit
  #   rev: 1.7.4
    # hooks:
    #   - id: bandit
    #     exclude: ^./expt-logs/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: ^./expt-logs/
  - repo: local
    hooks:
      - id: python-run-check
        name: Ensure Python scripts run
        entry: python
        args: ['-m', 'compileall', '.']
        language: system
        files: \.py$
